version: 2.1
orbs:
  cypress: cypress-io/cypress@1

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: npm install
          command: npm install
  test:
    - cypress/run:
        start: npm start
        parallelism: 4
  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run:
          name: deploy
          command: npx plek now cat-roulette.now.sh --app 'cat-roulette' -- --public

workflows:
  build_and_deploy:
    jobs:
      - build
      - test
      - deploy:
          filters:
            branches: 
              only:
                - master