version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:10.16.3

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: 
          name: npm install
          command: npm install
      - run:
          name: now scripts
          command: |
            npm install -g --unsafe-perm now
            node --version
            npm --version
            npm run deploy --silent -- --token $NOW_TOKEN
      # - run:
      #     name: install now
      #     command: npm i -g now --silent
      # - run:
      #     name: deploy to now
      #     command: |
      #       URL=$(now -t ${NOW_TOKEN} )
      #       NOW_URL=$(echo ${URL} | sed s/'http:\/\/'/''/g | sed s/'https:\/\/'//g)
      #       now -t ${NOW_TOKEN} cat-roulette.now.sh --app 'cat-roulette' -- --public

    # - URL=$(now -t ${NOW_TOKEN} )
    # - .NOW_URL=$(echo ${URL} | sed s/'http:\/\/'/''/g | sed s/'https:\/\/'//g)
    # - now -t ${NOW_TOKEN} alias set ${NOW_URL} staging.mydomain.com

      # - run: npx plek now cat-roulette.now.sh --app 'cat-roulette' -- --public

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches: 
              only:
                - master