version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:10.16.3

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: npm install
          command: npm install
      - run:
          name: tests
          command: npm run cypress:open
      - run:
          name: deploy
          command: npx plek now cat-roulette.now.sh --app 'cat-roulette' -- --public

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches: 
              only:
                - master