version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - run: npx plek now cat-roulette.now.sh --app 'cat-roulette' -- --public

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    # working_directory: ~/contracts
    docker: 
      - image: circleci/node:8-browsers
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
      - image: trufflesuite/ganache-cli
    steps:
      run: npm test #truffle testing
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
          - build