version: 2
jobs:
  build_and_test:
    # working_directory: ~/contracts
    docker: 
      - image: circleci/node:8-browsers
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
      - image: trufflesuite/ganache-cli

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: truffle test # triggers truffle test

  deploy:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - run: npx plek now cat-roulette.now.sh --app 'cat-roulette' -- --public

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  # test:
  #   # working_directory: ~/contracts
  #   docker: 
  #     - image: circleci/node:8-browsers
  #   # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
  #     - image: trufflesuite/ganache-cli
  #   steps:
  #     run: npm test #truffle testing

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
      # - deploy:
      #     requires:
      #       - build_and_test