version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: npm install
          command: npm install
  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run:
          name: deploy
          command: npx plek now cat-roulette.now.sh --app 'cat-roulette' -- --public

workflows:
  build_and_deploy:
    jobs:
      - build
      - cypress/run:
          start: npm start
          parallelism: 4
          requires: 
          - build
      - deploy:
          requires:
          - cypress/run
          filters:
            branches: 
              only:
                - master
      - slack/notify:
          channel: TJ7LRE38F
          webhook: https://hooks.slack.com/services/$SLACK_WEBHOOK