version: 2
jobs:
  #taking the below out for now.. need to work on testing local blockchain
  # build_and_test:
  #   docker: 
  #     - image: circleci/node:8-browsers
  #   # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
  #     - image: trufflesuite/ganache-cli

  #   steps:
  #     - checkout

  #     # Download and cache dependencies
  #     - restore_cache:
  #         keys:
  #         - v1-dependencies-{{ checksum "package.json" }}
  #         # fallback to using the latest cache if no exact match is found
  #         - v1-dependencies-

  #     - run: npm install
  #     # - run: npm install -g truffle
  #     - run: truffle migrate
  #     - run: truffle config -- network ropsten

  #     - save_cache:
  #         paths:
  #           - node_modules
  #         key: v1-dependencies-{{ checksum "package.json" }}

  #     - run: npm test # triggers truffle test

  deploy:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - run: npx plek now cat-roulette.now.sh --app 'cat-roulette' -- --public

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
        filters:
          branches: 
            only: master